global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "smartcopy"
    static_configs:
      - targets: ["smartcopy-agent:9090"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
